name: telegram message

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Telegram Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{github.actor}} triggered a ${{github.event_name}} event in ${{ github.repository }} repository.
