name: telegram-message

on:
  [push, pull_request]
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]

jobs:
  build:
    name: Telegram Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{github.actor}} triggered a ${{github.event_name}} event to ${{ github.ref }} in ${{ github.repository }} repository. (Commit ${{ github.sha }})
